version: "3.9"

services:
  owner-postgres:
    image: postgres:16
    container_name: owner-postgres

    environment:
      POSTGRES_DB: owner
      POSTGRES_USER: owner
      POSTGRES_PASSWORD: owner
      TZ: Asia/Phnom_Penh

    ports:
      - "5436:5432"

    volumes:
      - owner_pg_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U owner -d owner"]
      interval: 5s
      timeout: 5s
      retries: 5

    restart: unless-stopped

volumes:
  owner_pg_data:
